language: php

php:
  - 5.4
  - 5.5
#  - hhvm

env:
#  - DB=agnostic                                   #only database agnostic tests
  - DB=mysql DB_USER=root                         #only database tests against mysql
  - DB=pgsql DB_USER=postgres DB_NAME=postgres    #only database tests against postgresql
  - DB=sqlite

before_script:
  # Composer
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --prefer-source

  - if [ "$DB" != 'agnostic' ]; then ./tests/bin/setup.$DB.sh; fi   # setup only for integration tests

script:
  - ./tests/bin/phpunit.$DB.sh;

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml

#matrix:
#  allow_failures:
#    - php: hhvm
