language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - DB=agnostic                                   #only database agnostic tests
  - DB=mysql DB_USER=root                         #only database tests against mysql
  - DB=pgsql DB_USER=postgres DB_NAME=postgres    #only database tests against postgresql
  - DB=sqlite

before_script:
  # Composer
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --prefer-source

  - if [ "$DB" != 'agnostic' ]; then ./tests/bin/setup.$DB.sh; fi   # setup only for integration tests

script:
  - ./tests/bin/phpunit.$DB.sh;

after_script:
  - CODECLIMATE_REPO_TOKEN=92d285429bca0648ada4573f9673251098c1f33ed4ffd5106a10bcf5b9e151a8 ./vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 5.6
  exclude:
    - php: hhvm
      env: DB=pgsql DB_USER=postgres DB_NAME=postgres  # driver currently unsupported by HHVM
    - php: hhvm
      env: DB=sqlite # some issues at the moment